from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = 'public'
                      AND table_name = 'projects_skill'
                ) THEN
                    CREATE TABLE "projects_skill" (
                        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "name" varchar(124) NOT NULL UNIQUE
                    );
                END IF;

                IF NOT EXISTS (
                    SELECT 1
                    FROM information_schema.tables
                    WHERE table_schema = 'public'
                      AND table_name = 'projects_project_skills'
                ) THEN
                    CREATE TABLE "projects_project_skills" (
                        "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "project_id" bigint NOT NULL
                            REFERENCES "projects_project" ("id")
                            DEFERRABLE INITIALLY DEFERRED,
                        "skill_id" bigint NOT NULL
                            REFERENCES "projects_skill" ("id")
                            DEFERRABLE INITIALLY DEFERRED
                    );

                    CREATE UNIQUE INDEX "projects_project_skills_project_skill_uniq"
                        ON "projects_project_skills" ("project_id", "skill_id");
                    CREATE INDEX "projects_project_skills_project_id_idx"
                        ON "projects_project_skills" ("project_id");
                    CREATE INDEX "projects_project_skills_skill_id_idx"
                        ON "projects_project_skills" ("skill_id");
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
