USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
SKILL_NAME_MAX_LENGTH = 124

PROJECTS_PER_PAGE = 12
USERS_PER_PAGE = 12
SKILLS_AUTOCOMPLETE_LIMIT = 10

AVATAR_SIZE = 256
AVATAR_TEXT_COLOR = "#FFFFFF"
AVATAR_FORMAT = "PNG"
AVATAR_FONT_NAME = "arial.ttf"

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"
